server:
  port: 8189
  servlet:
    context-path: /zbrain
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zbrain?serverTimezone=Europe/Moscow&useSSL=false
    username: root
    password: 1233
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        temp:
          use_jdbc_metadata_defaults: false